<?php
/*
===================================================================================================
WARNING! DO NOT EDIT THIS FILE OR ANY TEMPLATE FILES IN THIS THEME!

To make it easy to update your theme, you should not edit this file. Instead, you should create a
Child Theme first. This will ensure your template changes are not lost when updating the theme.

You can learn more about creating Child Themes here: http://codex.wordpress.org/Child_Themes

You have been warned! :)
===================================================================================================
*/

// Theme options
define( 'CHURCHTHEMES_OPTIONS_MAIN_COLOR', '#629fa6' );
define( 'CHURCHTHEMES_OPTIONS_LOGO_WIDTH', 277 );
define( 'CHURCHTHEMES_OPTIONS_LOGO_HEIGHT', 25 );
define( 'CHURCHTHEMES_OPTIONS_LOGO_TOP_MARGIN', 32 );

// Custom background
// define( 'CHURCHTHEMES_DEFAULT_BACKGROUND_IMAGE',  WP_THEME_DIR . '/images/bg_body.jpg'  );
define( 'CHURCHTHEMES_DEFAULT_BACKGROUND_COLOR', 'd9d9d1' );

// Update script
define( 'CHURCHTHEMES_UPDATE_API_URL', 'http://churchthemes.net/updates/antioch/' );
